# Generated by Django 4.2.2 on 2023-07-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_image',
            field=models.ImageField(blank=True, default=None, upload_to='app/'),
        ),
    ]
