# Generated by Django 4.2.2 on 2023-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_apps', '0002_alter_app_app_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_image',
            field=models.ImageField(null=True, upload_to='app/'),
        ),
    ]
