# Generated by Django 4.2.2 on 2023-07-02 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mod_apps', '0004_alter_category_name_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('app', 'user')},
        ),
    ]
